name: åˆ†å‘æµ‹è¯•Apk

on:
  push:
    branches: [ dev ]

jobs:
  slack-notifications:
    runs-on: ubuntu-latest
    name: Upload test file
    steps:
      - uses: actions/checkout@v2
      - name: setup jdk8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: build apk file
        run: ./gradlew assembleDebug
      - name: Send message to Slack
        uses: archive/github-actions-slack@master
        with:
          slack-bot-user-oauth-access-token: ${{ secrets.SLACK_BOT_USER_OAUTH_ACCESS_TOKEN }}
          slack-channel: test
          slack-text: ${{ github.event.commits[0].message }} ğŸ¤“â›½ï¸ğŸ’ª
      - name: Result from "Send Message"
        run: echo "The result was ${{ steps.notify.outputs.slack-result }}"
      - name: Upload to slack step
        uses: adrey/slack-file-upload-action@master
        with:
          token: ${{ secrets.SLACK_ACCESS_TOKEN }}
          path: ./app/build/outputs/apk/debug/app-debug.apk
          channel: test
